
# This config file supports variable substitution which enables: 1) keeping
# secrets out of source control & 2) environment-based configuration changes
# such as staging vs prod.
#
# When GX encounters substitution syntax (like `my_key: ${my_value}` or
# `my_key: $my_value`) in the great_expectations.yml file, it will attempt
# to replace the value of `my_key` with the value from an environment
# variable `my_value` or a corresponding key read from this config file,
# which is defined through the `config_variables_file_path`.
# Environment variables take precedence over variables defined here.
#
# Substitution values defined here can be a simple (non-nested) value,
# nested value such as a dictionary, or an environment variable (i.e. ${ENV_VAR})
#
#
# https://docs.greatexpectations.io/docs/guides/setup/configuring_data_contexts/how_to_configure_credentials

instance_id: 52cbd5ec-c1d6-452e-85de-de99f8bb11d1


app_hosting_project: able-starlight-378102
app_bucket: eproc_datadocs_app

GCP_PROJECT: deep-contact-361614
BIGQUERY_DATASET: eproc_public

validation_notification_slack_webhook: https://hooks.slack.com/services/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